import { randomUUID } from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { env } from '../config/env.js';

export const DAILY_REPORT_ATTACHMENT_MAX_FILE_SIZE = 50 * 1024 * 1024;

// Daily report images are stored under the report export root but never served statically.
function getDailyReportAttachmentStorageDir() {
  return path.resolve(env.reports.exportRoot, '_attachments', 'daily-reports');
}

// Storage keys are generated by the server and never accepted from clients.
export function createDailyReportAttachmentStorageKey({ dailyReportId }) {
  return path.join(String(dailyReportId), `${Date.now()}-${randomUUID()}`);
}

// Resolve storage keys defensively to prevent path traversal.
export function getDailyReportAttachmentPath(storageKey) {
  const storageDir = getDailyReportAttachmentStorageDir();
  const resolved = path.resolve(storageDir, storageKey);

  if (!resolved.startsWith(`${storageDir}${path.sep}`)) {
    throw new Error('Invalid daily report attachment storage key');
  }

  return resolved;
}

// Persist an uploaded attachment using exclusive create semantics.
export async function writeDailyReportAttachmentFile(storageKey, buffer) {
  const filePath = getDailyReportAttachmentPath(storageKey);
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, buffer, { flag: 'wx' });
  const stat = await fs.stat(filePath);

  return {
    filePath,
    size: stat.size
  };
}

// Resolve and verify a stored attachment before download.
export async function assertDailyReportAttachmentFileReadable(storageKey) {
  const filePath = getDailyReportAttachmentPath(storageKey);
  await fs.access(filePath);
  return filePath;
}

// Cleanup is best-effort so database errors remain the primary failure.
export async function cleanupDailyReportAttachmentFile(storageKey) {
  if (!storageKey) {
    return;
  }

  try {
    await fs.unlink(getDailyReportAttachmentPath(storageKey));
  } catch (error) {
    if (error?.code !== 'ENOENT') {
      // Keep cleanup non-fatal to preserve the original business error.
    }
  }
}
