import {
  BUSINESS_DEPARTMENT,
  isCenterManagerOf,
  isGeneralManagerUser
} from './organization.js';
import { PROJECT_STATUS } from './projects.js';

export const CONTRACT_SIGNING_STAGE = {
  STAGE_ORDER: 3,
  STAGE_KEY: 'contract',
  STAGE_NAME: '合同签订阶段'
};

export const CONTRACT_SIGNING_NODE_KEY = {
  CONTRACT_PREPARATION: 'contract_preparation',
  CONTRACT_SIGNING: 'contract_signing',
  ADVANCE_PAYMENT: 'advance_payment',
  // Deprecated: kept only so old deep links/API calls can be rejected explicitly.
  PROJECT_KICKOFF_NOTICE: 'project_kickoff_notice'
};

export const CONTRACT_SIGNING_NODE_STATUS = {
  NOT_STARTED: 'not_started',
  PENDING: 'pending',
  PENDING_REVIEW: 'pending_review',
  WAITING_GENERAL_MANAGER: 'waiting_general_manager',
  RETURNED: 'returned',
  APPROVED: 'approved'
};

export const CONTRACT_SIGNING_NODES = Object.freeze([
  {
    nodeKey: CONTRACT_SIGNING_NODE_KEY.CONTRACT_PREPARATION,
    nodeName: '准备协议和合同',
    nodeOrder: 1
  },
  {
    nodeKey: CONTRACT_SIGNING_NODE_KEY.CONTRACT_SIGNING,
    nodeName: '签订协议和合同',
    nodeOrder: 2
  },
  {
    nodeKey: CONTRACT_SIGNING_NODE_KEY.ADVANCE_PAYMENT,
    nodeName: '项目预付款支付',
    nodeOrder: 3
  }
]);

export const CONTRACT_SIGNING_UPLOAD_SLOT_KEY = {
  TECHNICAL_AGREEMENT: 'technical_agreement',
  SALES_CONTRACT: 'sales_contract',
  TECHNICAL_AGREEMENT_SCAN: 'technical_agreement_scan',
  SALES_CONTRACT_SCAN: 'sales_contract_scan',
  // Deprecated: kickoff notice is generated by advance_payment final actions.
  PROJECT_KICKOFF_NOTICE: 'project_kickoff_notice'
};

export const CONTRACT_SIGNING_UPLOAD_SLOT_STATUS = {
  PENDING: 'pending',
  UPLOADED: 'uploaded',
  SUBMITTED: 'submitted',
  APPROVED: 'approved',
  RETURNED: 'returned'
};

export const CONTRACT_SIGNING_REVIEW_STATUS = {
  PENDING: 'pending',
  APPROVED: 'approved',
  RETURNED: 'returned'
};

export const CONTRACT_SIGNING_CONFIRMATION_STATUS = {
  PENDING: 'pending',
  APPROVED: 'approved',
  RETURNED: 'returned'
};

export const CONTRACT_SIGNING_PAYMENT_STATUS = {
  NOT_STARTED: 'not_started',
  PENDING: 'pending',
  COMPLETED: 'completed',
  WAITING_GENERAL_MANAGER: 'waiting_general_manager',
  RELEASED: 'released'
};

export const CONTRACT_SIGNING_ROLE_KEY = {
  TECHNICAL_OWNER: 'technical_owner',
  BUSINESS_OWNER: 'business_owner'
};

export const CONTRACT_SIGNING_UPLOAD_SLOTS = Object.freeze([
  {
    slotKey: CONTRACT_SIGNING_UPLOAD_SLOT_KEY.TECHNICAL_AGREEMENT,
    slotName: '技术协议',
    nodeKey: CONTRACT_SIGNING_NODE_KEY.CONTRACT_PREPARATION,
    slotOrder: 1,
    requiredRoleKey: CONTRACT_SIGNING_ROLE_KEY.TECHNICAL_OWNER,
    reviewDepartment: BUSINESS_DEPARTMENT.RD_CENTER
  },
  {
    slotKey: CONTRACT_SIGNING_UPLOAD_SLOT_KEY.SALES_CONTRACT,
    slotName: '销售合同',
    nodeKey: CONTRACT_SIGNING_NODE_KEY.CONTRACT_PREPARATION,
    slotOrder: 2,
    requiredRoleKey: CONTRACT_SIGNING_ROLE_KEY.BUSINESS_OWNER,
    reviewDepartment: BUSINESS_DEPARTMENT.MARKETING_CENTER
  },
  {
    slotKey: CONTRACT_SIGNING_UPLOAD_SLOT_KEY.TECHNICAL_AGREEMENT_SCAN,
    slotName: '技术协议扫描件',
    nodeKey: CONTRACT_SIGNING_NODE_KEY.CONTRACT_SIGNING,
    slotOrder: 3,
    requiredRoleKey: CONTRACT_SIGNING_ROLE_KEY.BUSINESS_OWNER
  },
  {
    slotKey: CONTRACT_SIGNING_UPLOAD_SLOT_KEY.SALES_CONTRACT_SCAN,
    slotName: '销售合同扫描件',
    nodeKey: CONTRACT_SIGNING_NODE_KEY.CONTRACT_SIGNING,
    slotOrder: 4,
    requiredRoleKey: CONTRACT_SIGNING_ROLE_KEY.BUSINESS_OWNER
  }
]);

export const CONTRACT_SIGNING_ERROR = {
  FORBIDDEN: 'CONTRACT_SIGNING_FORBIDDEN',
  PROJECT_ENDED: 'CONTRACT_SIGNING_PROJECT_ENDED',
  NOT_IN_STAGE: 'CONTRACT_SIGNING_NOT_IN_STAGE',
  INVALID_NODE: 'CONTRACT_SIGNING_INVALID_NODE',
  INVALID_UPLOAD_SLOT: 'CONTRACT_SIGNING_INVALID_UPLOAD_SLOT',
  INVALID_UPLOAD_FILE: 'CONTRACT_SIGNING_INVALID_UPLOAD_FILE',
  UPLOAD_FILE_NOT_FOUND: 'CONTRACT_SIGNING_UPLOAD_FILE_NOT_FOUND',
  NODE_NOT_PROCESSABLE: 'CONTRACT_SIGNING_NODE_NOT_PROCESSABLE',
  UPLOAD_SLOT_NOT_PROCESSABLE: 'CONTRACT_SIGNING_UPLOAD_SLOT_NOT_PROCESSABLE',
  RETURN_REASON_REQUIRED: 'CONTRACT_SIGNING_RETURN_REASON_REQUIRED',
  DEPRECATED_ACTION: 'CONTRACT_SIGNING_DEPRECATED_ACTION'
};

export class ContractSigningWorkflowError extends Error {
  constructor(code, message, statusCode = 409, details = []) {
    super(message);
    this.name = 'ContractSigningWorkflowError';
    this.code = code;
    this.statusCode = statusCode;
    this.details = details;
  }
}

export function buildInitialContractSigningNodes() {
  return CONTRACT_SIGNING_NODES.map((node, index) => ({
    ...node,
    status: index === 0
      ? CONTRACT_SIGNING_NODE_STATUS.PENDING
      : CONTRACT_SIGNING_NODE_STATUS.NOT_STARTED
  }));
}

export function getContractSigningNodeDefinition(nodeKey) {
  return CONTRACT_SIGNING_NODES.find((node) => node.nodeKey === nodeKey) || null;
}

export function getContractSigningUploadSlotDefinition(slotKey) {
  return CONTRACT_SIGNING_UPLOAD_SLOTS.find((slot) => slot.slotKey === slotKey) || null;
}

export function isProjectInContractSigningStage(project) {
  return (
    project?.current_stage_key === CONTRACT_SIGNING_STAGE.STAGE_KEY ||
    project?.currentStage?.stageKey === CONTRACT_SIGNING_STAGE.STAGE_KEY
  );
}

export function hasReachedContractSigningStage(project) {
  const currentStageOrder = Number(project?.current_stage_order ?? project?.currentStage?.stageOrder ?? 0);
  return Number.isFinite(currentStageOrder) && currentStageOrder >= CONTRACT_SIGNING_STAGE.STAGE_ORDER;
}

export function isContractSigningProjectEnded(project) {
  return project?.status === PROJECT_STATUS.ENDED;
}

export function isContractSigningRdCenterManager(user) {
  return isCenterManagerOf(user, BUSINESS_DEPARTMENT.RD_CENTER);
}

export function isContractSigningMarketingCenterManager(user) {
  return isCenterManagerOf(user, BUSINESS_DEPARTMENT.MARKETING_CENTER);
}

export function isContractSigningGeneralManager(user) {
  return isGeneralManagerUser(user);
}

export { BUSINESS_DEPARTMENT };
