import { BUSINESS_DEPARTMENT } from './organization.js';

const {
  MARKETING_CENTER,
  MANUFACTURING_CENTER,
  RD_CENTER
} = BUSINESS_DEPARTMENT;

const STAGE_DOCUMENT_TEMPLATE_ITEMS_V20260610_RAW = Object.freeze([
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 1,
    stageKey: 'initiation',
    stageName: '立项阶段',
    documentCode: '1.1',
    documentOrder: 1,
    documentName: '项目需求表',
    isRequired: true,
    defaultResponsibilityRole: '营销人员',
    confirmRole: '营销中心/项目经理',
    submitMode: 'online_form',
    targetFolderPath: '1-立项/1.1 项目需求表',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 1,
    stageKey: 'initiation',
    stageName: '立项阶段',
    documentCode: '1.2',
    documentOrder: 2,
    documentName: '项目立项审批表',
    isRequired: true,
    defaultResponsibilityRole: '营销人员',
    confirmRole: '商务、技术、总经理等线下审批',
    submitMode: 'mixed',
    targetFolderPath: '1-立项/1.2 项目立项审批表',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 1,
    stageKey: 'initiation',
    stageName: '立项阶段',
    documentCode: '1.3',
    documentOrder: 3,
    documentName: '项目立项通知',
    isRequired: true,
    defaultResponsibilityRole: '营销总监',
    confirmRole: '营销中心',
    submitMode: 'file_upload',
    targetFolderPath: '1-立项/1.3 项目立项通知',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 1,
    stageKey: 'initiation',
    stageName: '立项阶段',
    documentCode: '1.4',
    documentOrder: 4,
    documentName: '方案设计工作计划',
    isRequired: true,
    defaultResponsibilityRole: '项目经理',
    confirmRole: '项目经理',
    submitMode: 'online_form',
    targetFolderPath: '1-立项/1.4 方案设计工作计划',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 2,
    stageKey: 'solution',
    stageName: '方案设计阶段',
    documentCode: '2.1',
    documentOrder: 1,
    documentName: '项目需求分析表',
    isRequired: true,
    defaultResponsibilityRole: '技术负责人',
    confirmRole: '项目经理',
    submitMode: 'online_form',
    targetFolderPath: '2-方案设计/2.1 项目需求分析表',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 2,
    stageKey: 'solution',
    stageName: '方案设计阶段',
    documentCode: '2.2',
    documentOrder: 2,
    documentName: '产品功能框图',
    isRequired: true,
    defaultResponsibilityRole: '技术负责人',
    confirmRole: '技术负责人',
    submitMode: 'file_upload',
    targetFolderPath: '2-方案设计/2.2 产品功能框图',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 2,
    stageKey: 'solution',
    stageName: '方案设计阶段',
    documentCode: '2.3',
    documentOrder: 3,
    documentName: '3D模型',
    isRequired: true,
    defaultResponsibilityRole: '机械/方案设计人员',
    confirmRole: '技术负责人',
    submitMode: 'file_upload',
    targetFolderPath: '2-方案设计/2.3 3D模型',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 2,
    stageKey: 'solution',
    stageName: '方案设计阶段',
    documentCode: '2.4',
    documentOrder: 4,
    documentName: '布局图',
    isRequired: true,
    defaultResponsibilityRole: '机械/方案设计人员',
    confirmRole: '技术负责人',
    submitMode: 'file_upload',
    targetFolderPath: '2-方案设计/2.4 布局图',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 2,
    stageKey: 'solution',
    stageName: '方案设计阶段',
    documentCode: '2.5',
    documentOrder: 5,
    documentName: '工艺时序图',
    isRequired: false,
    defaultResponsibilityRole: '技术负责人/工艺负责人',
    confirmRole: '技术负责人',
    submitMode: 'file_upload',
    targetFolderPath: '2-方案设计/2.5 工艺时序图',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 2,
    stageKey: 'solution',
    stageName: '方案设计阶段',
    documentCode: '2.6',
    documentOrder: 6,
    documentName: '节拍表',
    isRequired: false,
    defaultResponsibilityRole: '技术负责人/工艺负责人',
    confirmRole: '技术负责人',
    submitMode: 'file_upload',
    targetFolderPath: '2-方案设计/2.6 节拍表',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 2,
    stageKey: 'solution',
    stageName: '方案设计阶段',
    documentCode: '2.7',
    documentOrder: 7,
    documentName: '演示动画',
    isRequired: false,
    defaultResponsibilityRole: '机械/方案设计人员',
    confirmRole: '项目经理',
    submitMode: 'file_upload',
    targetFolderPath: '2-方案设计/2.7 演示动画',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 2,
    stageKey: 'solution',
    stageName: '方案设计阶段',
    documentCode: '2.8',
    documentOrder: 8,
    documentName: '电气功能框图',
    isRequired: true,
    defaultResponsibilityRole: '电气工程师',
    confirmRole: '技术负责人',
    submitMode: 'file_upload',
    targetFolderPath: '2-方案设计/2.8 电气功能框图',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 2,
    stageKey: 'solution',
    stageName: '方案设计阶段',
    documentCode: '2.9',
    documentOrder: 9,
    documentName: '软件功能框图',
    isRequired: true,
    defaultResponsibilityRole: '软件工程师',
    confirmRole: '技术负责人',
    submitMode: 'file_upload',
    targetFolderPath: '2-方案设计/2.9 软件功能框图',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 2,
    stageKey: 'solution',
    stageName: '方案设计阶段',
    documentCode: '2.10',
    documentOrder: 10,
    documentName: '内部方案评审记录表',
    isRequired: true,
    defaultResponsibilityRole: '技术负责人',
    confirmRole: '项目经理',
    submitMode: 'online_form',
    targetFolderPath: '2-方案设计/2.10 内部方案评审记录表',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 2,
    stageKey: 'solution',
    stageName: '方案设计阶段',
    documentCode: '2.11',
    documentOrder: 11,
    documentName: '成本估算表',
    isRequired: true,
    defaultResponsibilityRole: '各专业组成员、技术负责人',
    confirmRole: '制造中心',
    submitMode: 'mixed',
    targetFolderPath: '2-方案设计/2.11 成本估算表',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 2,
    stageKey: 'solution',
    stageName: '方案设计阶段',
    documentCode: '2.12',
    documentOrder: 12,
    documentName: '项目方案PPT',
    isRequired: true,
    defaultResponsibilityRole: '技术负责人',
    confirmRole: '项目经理',
    submitMode: 'file_upload',
    targetFolderPath: '2-方案设计/2.12 项目方案PPT',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 2,
    stageKey: 'solution',
    stageName: '方案设计阶段',
    documentCode: '2.13',
    documentOrder: 13,
    documentName: '客户方案评审记录表',
    isRequired: true,
    defaultResponsibilityRole: '技术负责人',
    confirmRole: '营销人员/项目经理',
    submitMode: 'online_form',
    targetFolderPath: '2-方案设计/2.13 客户方案评审记录表',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 3,
    stageKey: 'contract',
    stageName: '合同签订阶段',
    documentCode: '3.1',
    documentOrder: 1,
    documentName: '技术协议',
    isRequired: true,
    defaultResponsibilityRole: '技术负责人',
    confirmRole: '项目经理/营销中心',
    submitMode: 'mixed',
    targetFolderPath: '3-合同签订/3.1 技术协议',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 3,
    stageKey: 'contract',
    stageName: '合同签订阶段',
    documentCode: '3.2',
    documentOrder: 2,
    documentName: '销售合同',
    isRequired: true,
    defaultResponsibilityRole: '营销人员',
    confirmRole: '营销中心/总经理',
    submitMode: 'file_upload',
    targetFolderPath: '3-合同签订/3.2 销售合同',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 3,
    stageKey: 'contract',
    stageName: '合同签订阶段',
    documentCode: '3.3',
    documentOrder: 3,
    documentName: '项目启动书',
    isRequired: true,
    defaultResponsibilityRole: '制造中心',
    confirmRole: '制造中心',
    submitMode: 'file_upload',
    targetFolderPath: '3-合同签订/3.3 项目启动书',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 3,
    stageKey: 'contract',
    stageName: '合同签订阶段',
    documentCode: '3.4',
    documentOrder: 4,
    documentName: '详细设计工作计划',
    isRequired: true,
    defaultResponsibilityRole: '项目经理',
    confirmRole: '项目经理',
    submitMode: 'online_form',
    targetFolderPath: '3-合同签订/3.4 详细设计工作计划',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 4,
    stageKey: 'detailedDesign',
    stageName: '详细设计阶段',
    documentCode: '4.1',
    documentOrder: 1,
    documentName: '3D模型',
    isRequired: true,
    defaultResponsibilityRole: '机械工程师',
    confirmRole: '技术负责人',
    submitMode: 'file_upload',
    targetFolderPath: '4-详细设计/4.1 3D模型',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 4,
    stageKey: 'detailedDesign',
    stageName: '详细设计阶段',
    documentCode: '4.2',
    documentOrder: 2,
    documentName: '电气原理图',
    isRequired: true,
    defaultResponsibilityRole: '电气工程师',
    confirmRole: '技术负责人',
    submitMode: 'file_upload',
    targetFolderPath: '4-详细设计/4.2 电气原理图',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 4,
    stageKey: 'detailedDesign',
    stageName: '详细设计阶段',
    documentCode: '4.3',
    documentOrder: 3,
    documentName: '电气接线图',
    isRequired: true,
    defaultResponsibilityRole: '电气工程师',
    confirmRole: '技术负责人',
    submitMode: 'file_upload',
    targetFolderPath: '4-详细设计/4.3 电气接线图',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 4,
    stageKey: 'detailedDesign',
    stageName: '详细设计阶段',
    documentCode: '4.4',
    documentOrder: 4,
    documentName: '电气布置图',
    isRequired: true,
    defaultResponsibilityRole: '电气工程师',
    confirmRole: '技术负责人',
    submitMode: 'file_upload',
    targetFolderPath: '4-详细设计/4.4 电气布置图',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 4,
    stageKey: 'detailedDesign',
    stageName: '详细设计阶段',
    documentCode: '4.5',
    documentOrder: 5,
    documentName: '控制逻辑流程图',
    isRequired: true,
    defaultResponsibilityRole: '软件/自动化工程师',
    confirmRole: '技术负责人',
    submitMode: 'file_upload',
    targetFolderPath: '4-详细设计/4.5 控制逻辑流程图',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 4,
    stageKey: 'detailedDesign',
    stageName: '详细设计阶段',
    documentCode: '4.6',
    documentOrder: 6,
    documentName: '自动化程序',
    isRequired: true,
    defaultResponsibilityRole: '软件/自动化工程师',
    confirmRole: '技术负责人',
    submitMode: 'file_upload',
    targetFolderPath: '4-详细设计/4.6 自动化程序',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 4,
    stageKey: 'detailedDesign',
    stageName: '详细设计阶段',
    documentCode: '4.7',
    documentOrder: 7,
    documentName: '软件开发说明文档',
    isRequired: true,
    defaultResponsibilityRole: '软件工程师',
    confirmRole: '技术负责人',
    submitMode: 'file_upload',
    targetFolderPath: '4-详细设计/4.7 软件开发说明文档',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 4,
    stageKey: 'detailedDesign',
    stageName: '详细设计阶段',
    documentCode: '4.8',
    documentOrder: 8,
    documentName: 'UI界面设计PPT',
    isRequired: true,
    defaultResponsibilityRole: '软件/UI人员',
    confirmRole: '技术负责人',
    submitMode: 'file_upload',
    targetFolderPath: '4-详细设计/4.8 UI界面设计PPT',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 4,
    stageKey: 'detailedDesign',
    stageName: '详细设计阶段',
    documentCode: '4.9',
    documentOrder: 9,
    documentName: '软件代码',
    isRequired: true,
    defaultResponsibilityRole: '软件工程师',
    confirmRole: '技术负责人',
    submitMode: 'file_upload',
    targetFolderPath: '4-详细设计/4.9 软件代码',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 4,
    stageKey: 'detailedDesign',
    stageName: '详细设计阶段',
    documentCode: '4.10',
    documentOrder: 10,
    documentName: '内部设计评审记录表',
    isRequired: true,
    defaultResponsibilityRole: '技术负责人',
    confirmRole: '项目经理',
    submitMode: 'online_form',
    targetFolderPath: '4-详细设计/4.10 内部设计评审记录表',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 4,
    stageKey: 'detailedDesign',
    stageName: '详细设计阶段',
    documentCode: '4.11',
    documentOrder: 11,
    documentName: '客户设计评审记录表',
    isRequired: true,
    defaultResponsibilityRole: '技术负责人',
    confirmRole: '营销人员/项目经理',
    submitMode: 'online_form',
    targetFolderPath: '4-详细设计/4.11 客户设计评审记录表',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 4,
    stageKey: 'detailedDesign',
    stageName: '详细设计阶段',
    documentCode: '4.12',
    documentOrder: 12,
    documentName: '产品平面图',
    isRequired: true,
    defaultResponsibilityRole: '机械工程师',
    confirmRole: '技术负责人',
    submitMode: 'file_upload',
    targetFolderPath: '4-详细设计/4.12 产品平面图',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 4,
    stageKey: 'detailedDesign',
    stageName: '详细设计阶段',
    documentCode: '4.13',
    documentOrder: 13,
    documentName: '产品零部件清单',
    isRequired: true,
    defaultResponsibilityRole: '各专业组成员、技术负责人',
    confirmRole: '技术负责人',
    submitMode: 'mixed',
    targetFolderPath: '4-详细设计/4.13 产品零部件清单',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 4,
    stageKey: 'detailedDesign',
    stageName: '详细设计阶段',
    documentCode: '4.14',
    documentOrder: 14,
    documentName: '图纸审查记录',
    isRequired: true,
    defaultResponsibilityRole: '图纸审查人员',
    confirmRole: '项目经理/研发总监',
    submitMode: 'online_form',
    targetFolderPath: '4-详细设计/4.14 图纸审查记录',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 4,
    stageKey: 'detailedDesign',
    stageName: '详细设计阶段',
    documentCode: '4.15',
    documentOrder: 15,
    documentName: '客户会签记录',
    isRequired: true,
    defaultResponsibilityRole: '营销人员/项目经理',
    confirmRole: '项目经理',
    submitMode: 'file_upload',
    targetFolderPath: '4-详细设计/4.15 客户会签记录',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 4,
    stageKey: 'detailedDesign',
    stageName: '详细设计阶段',
    documentCode: '4.16',
    documentOrder: 16,
    documentName: '技术通知单',
    isRequired: true,
    defaultResponsibilityRole: '技术负责人',
    confirmRole: '项目经理/制造中心',
    submitMode: 'mixed',
    targetFolderPath: '4-详细设计/4.16 技术通知单',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 5,
    stageKey: 'manufacturing',
    stageName: '生产制作阶段',
    documentCode: '5.1',
    documentOrder: 1,
    documentName: '比价表',
    isRequired: true,
    defaultResponsibilityRole: '制造中心人员',
    confirmRole: '制造中心',
    submitMode: 'mixed',
    targetFolderPath: '5-生产制作/5.1 比价表',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 5,
    stageKey: 'manufacturing',
    stageName: '生产制作阶段',
    documentCode: '5.2',
    documentOrder: 2,
    documentName: '采购合同',
    isRequired: true,
    defaultResponsibilityRole: '制造中心人员',
    confirmRole: '制造中心',
    submitMode: 'file_upload',
    targetFolderPath: '5-生产制作/5.2 采购合同',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 5,
    stageKey: 'manufacturing',
    stageName: '生产制作阶段',
    documentCode: '5.3',
    documentOrder: 3,
    documentName: '检验单',
    isRequired: true,
    defaultResponsibilityRole: '制造中心人员',
    confirmRole: '制造中心',
    submitMode: 'mixed',
    targetFolderPath: '5-生产制作/5.3 检验单',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 5,
    stageKey: 'manufacturing',
    stageName: '生产制作阶段',
    documentCode: '5.4',
    documentOrder: 4,
    documentName: '入库单',
    isRequired: true,
    defaultResponsibilityRole: '制造中心人员',
    confirmRole: '制造中心',
    submitMode: 'mixed',
    targetFolderPath: '5-生产制作/5.4 入库单',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 5,
    stageKey: 'manufacturing',
    stageName: '生产制作阶段',
    documentCode: '5.5',
    documentOrder: 5,
    documentName: '领料单',
    isRequired: true,
    defaultResponsibilityRole: '制造中心人员',
    confirmRole: '制造中心',
    submitMode: 'mixed',
    targetFolderPath: '5-生产制作/5.5 领料单',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 6,
    stageKey: 'preAcceptance',
    stageName: '预验收阶段',
    documentCode: '6.1',
    documentOrder: 1,
    documentName: '作业指导书',
    isRequired: true,
    defaultResponsibilityRole: '技术负责人',
    confirmRole: '技术负责人',
    submitMode: 'mixed',
    targetFolderPath: '6-预验收/6.1 作业指导书',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 6,
    stageKey: 'preAcceptance',
    stageName: '预验收阶段',
    documentCode: '6.2',
    documentOrder: 2,
    documentName: '产品使用说明书',
    isRequired: true,
    defaultResponsibilityRole: '技术负责人',
    confirmRole: '项目经理/技术负责人',
    submitMode: 'mixed',
    targetFolderPath: '6-预验收/6.2 产品使用说明书',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 6,
    stageKey: 'preAcceptance',
    stageName: '预验收阶段',
    documentCode: '6.3',
    documentOrder: 3,
    documentName: '产品维护保养手册',
    isRequired: true,
    defaultResponsibilityRole: '技术负责人',
    confirmRole: '项目经理/技术负责人',
    submitMode: 'file_upload',
    targetFolderPath: '6-预验收/6.3 产品维护保养手册',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 6,
    stageKey: 'preAcceptance',
    stageName: '预验收阶段',
    documentCode: '6.4',
    documentOrder: 4,
    documentName: '产品培训PPT',
    isRequired: true,
    defaultResponsibilityRole: '技术负责人',
    confirmRole: '项目经理/技术负责人',
    submitMode: 'file_upload',
    targetFolderPath: '6-预验收/6.4 产品培训PPT',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 6,
    stageKey: 'preAcceptance',
    stageName: '预验收阶段',
    documentCode: '6.5',
    documentOrder: 5,
    documentName: '安装调试记录',
    isRequired: true,
    defaultResponsibilityRole: '制造中心人员',
    confirmRole: '制造中心',
    submitMode: 'mixed',
    targetFolderPath: '6-预验收/6.5 安装调试记录',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 6,
    stageKey: 'preAcceptance',
    stageName: '预验收阶段',
    documentCode: '6.6',
    documentOrder: 6,
    documentName: '自验收报告',
    isRequired: true,
    defaultResponsibilityRole: '制造中心人员',
    confirmRole: '制造中心',
    submitMode: 'mixed',
    targetFolderPath: '6-预验收/6.6 自验收报告',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 6,
    stageKey: 'preAcceptance',
    stageName: '预验收阶段',
    documentCode: '6.7',
    documentOrder: 7,
    documentName: '预验收单',
    isRequired: true,
    defaultResponsibilityRole: '制造中心人员',
    confirmRole: '营销中心/项目经理',
    submitMode: 'mixed',
    targetFolderPath: '6-预验收/6.7 预验收单',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 7,
    stageKey: 'finalAcceptance',
    stageName: '终验收阶段',
    documentCode: '7.1',
    documentOrder: 1,
    documentName: '发货单',
    isRequired: true,
    defaultResponsibilityRole: '制造中心人员',
    confirmRole: '制造中心',
    submitMode: 'mixed',
    targetFolderPath: '7-终验收/7.1 发货单',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 7,
    stageKey: 'finalAcceptance',
    stageName: '终验收阶段',
    documentCode: '7.2',
    documentOrder: 2,
    documentName: '安装调试记录',
    isRequired: true,
    defaultResponsibilityRole: '制造中心人员',
    confirmRole: '制造中心',
    submitMode: 'mixed',
    targetFolderPath: '7-终验收/7.2 安装调试记录',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 7,
    stageKey: 'finalAcceptance',
    stageName: '终验收阶段',
    documentCode: '7.3',
    documentOrder: 3,
    documentName: '终验收单',
    isRequired: true,
    defaultResponsibilityRole: '制造中心人员',
    confirmRole: '营销中心/项目经理',
    submitMode: 'mixed',
    targetFolderPath: '7-终验收/7.3 终验收单',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 7,
    stageKey: 'finalAcceptance',
    stageName: '终验收阶段',
    documentCode: '7.4',
    documentOrder: 4,
    documentName: '培训记录表',
    isRequired: true,
    defaultResponsibilityRole: '培训主讲人员',
    confirmRole: '营销中心/项目经理',
    submitMode: 'online_form',
    targetFolderPath: '7-终验收/7.4 培训记录表',
    targetFolderId: null
  }),
  Object.freeze({
    templateVersion: 'v20260610',
    stageOrder: 8,
    stageKey: 'closeout',
    stageName: '结题阶段',
    documentCode: '8.1',
    documentOrder: 1,
    documentName: '项目结题报告',
    isRequired: true,
    defaultResponsibilityRole: '项目经理',
    confirmRole: '总经理/相关负责人',
    submitMode: 'mixed',
    targetFolderPath: '8-结题/8.1 项目结题报告',
    targetFolderId: null
  })
]);

const DOCUMENT_DEPARTMENT_OWNERSHIP = Object.freeze({
  '1.1': { ownerDepartment: MARKETING_CENTER, reviewDepartment: MARKETING_CENTER },
  '1.2': { ownerDepartment: MARKETING_CENTER, reviewDepartment: MARKETING_CENTER },
  '1.3': { ownerDepartment: MARKETING_CENTER, reviewDepartment: MARKETING_CENTER },
  '1.4': { ownerDepartment: null, reviewDepartment: null },
  '2.1': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '2.2': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '2.3': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '2.4': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '2.5': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '2.6': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '2.7': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '2.8': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '2.9': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '2.10': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '2.11': { ownerDepartment: RD_CENTER, reviewDepartment: MANUFACTURING_CENTER },
  '2.12': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '2.13': { ownerDepartment: MARKETING_CENTER, reviewDepartment: MARKETING_CENTER },
  '3.1': { ownerDepartment: RD_CENTER, reviewDepartment: MARKETING_CENTER },
  '3.2': { ownerDepartment: MARKETING_CENTER, reviewDepartment: MARKETING_CENTER },
  '3.3': { ownerDepartment: MANUFACTURING_CENTER, reviewDepartment: MANUFACTURING_CENTER },
  '3.4': { ownerDepartment: null, reviewDepartment: null },
  '4.1': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '4.2': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '4.3': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '4.4': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '4.5': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '4.6': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '4.7': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '4.8': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '4.9': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '4.10': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '4.11': { ownerDepartment: MARKETING_CENTER, reviewDepartment: MARKETING_CENTER },
  '4.12': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '4.13': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '4.14': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '4.15': { ownerDepartment: MARKETING_CENTER, reviewDepartment: MARKETING_CENTER },
  '4.16': { ownerDepartment: RD_CENTER, reviewDepartment: MANUFACTURING_CENTER },
  '5.1': { ownerDepartment: MANUFACTURING_CENTER, reviewDepartment: MANUFACTURING_CENTER },
  '5.2': { ownerDepartment: MANUFACTURING_CENTER, reviewDepartment: MANUFACTURING_CENTER },
  '5.3': { ownerDepartment: MANUFACTURING_CENTER, reviewDepartment: MANUFACTURING_CENTER },
  '5.4': { ownerDepartment: MANUFACTURING_CENTER, reviewDepartment: MANUFACTURING_CENTER },
  '5.5': { ownerDepartment: MANUFACTURING_CENTER, reviewDepartment: MANUFACTURING_CENTER },
  '6.1': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '6.2': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '6.3': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '6.4': { ownerDepartment: RD_CENTER, reviewDepartment: RD_CENTER },
  '6.5': { ownerDepartment: MANUFACTURING_CENTER, reviewDepartment: MANUFACTURING_CENTER },
  '6.6': { ownerDepartment: MANUFACTURING_CENTER, reviewDepartment: MANUFACTURING_CENTER },
  '6.7': { ownerDepartment: MANUFACTURING_CENTER, reviewDepartment: MARKETING_CENTER },
  '7.1': { ownerDepartment: MANUFACTURING_CENTER, reviewDepartment: MANUFACTURING_CENTER },
  '7.2': { ownerDepartment: MANUFACTURING_CENTER, reviewDepartment: MANUFACTURING_CENTER },
  '7.3': { ownerDepartment: MANUFACTURING_CENTER, reviewDepartment: MARKETING_CENTER },
  '7.4': { ownerDepartment: MARKETING_CENTER, reviewDepartment: MARKETING_CENTER },
  '8.1': { ownerDepartment: null, reviewDepartment: null }
});

export const STAGE_DOCUMENT_TEMPLATE_ITEMS_V20260610 = Object.freeze(
  STAGE_DOCUMENT_TEMPLATE_ITEMS_V20260610_RAW.map((item) =>
    Object.freeze({
      ...item,
      ...DOCUMENT_DEPARTMENT_OWNERSHIP[item.documentCode]
    })
  )
);
